name: Lighthouse
on: [push, pull_request]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: mkdir -p ${{ github.workspace }}/tmp/artifacts
    - name: Lighthouse-desktop
      uses: foo-software/lighthouse-check-action@master
      id: lighthouseCheckDesktop
      with:
        urls: 'https://bucketlisty.com/'
        outputDirectory: ${{ github.workspace }}/tmp/artifacts
        accessToken: ${{ secrets.LIGHTHOUSE_CHECK_GITHUB_ACCESS_TOKEN }}
        commentUrl: 'https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/comments'
        prCommentEnabled: true
        device: 'desktop'
        wait: true
    - name: Lighthouse-mobile
      uses: foo-software/lighthouse-check-action@master 
      id: lighthouseCheckMobile
      with:
        urls: 'https://bucketlisty.com/'
        outputDirectory: ${{ github.workspace }}/tmp/artifacts
        accessToken: ${{ secrets.LIGHTHOUSE_CHECK_GITHUB_ACCESS_TOKEN }}
        commentUrl: 'https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/comments'
        prCommentEnabled: true
        device: 'mobile'
        wait: true
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: Lighthouse reports
        path: ${{ github.workspace }}/tmp/artifacts
    - name: Verify Lighthouse Check desktop results
      uses: foo-software/lighthouse-check-status-action@master
      with:
        lighthouseCheckResults: ${{ steps.lighthouseCheckDesktop.outputs.lighthouseCheckResults }}
        minAccessibilityScore: "80"
        minBestPracticesScore: "60"
        minPerformanceScore: "70"
        minProgressiveWebAppScore: "0"
        minSeoScore: "70"
    - name: Verify Lighthouse Check mobile results
      uses: foo-software/lighthouse-check-status-action@master
      with:
        lighthouseCheckResults: ${{ steps.lighthouseCheckMobile.outputs.lighthouseCheckResults }}
        minAccessibilityScore: "80"
        minBestPracticesScore: "60"
        minPerformanceScore: "30"
        minProgressiveWebAppScore: "0"
        minSeoScore: "70"
