name: Lighthouse
on: [push, pull_request]

jobs:
  lighthouse-desktop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Lighthouse
      uses: foo-software/lighthouse-check-action@master
      with:
        urls: 'https://bucketlisty.com/'
        accessToken: ${{ secrets.LIGHTHOUSE_CHECK_GITHUB_ACCESS_TOKEN }}
        commentUrl: 'https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/comments'
        prCommentEnabled: true
        device: 'desktop'
        wait: true
  lighthouse-mobile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Lighthouse
      uses: foo-software/lighthouse-check-action@master
      with:
        urls: 'https://bucketlisty.com/'
        accessToken: ${{ secrets.LIGHTHOUSE_CHECK_GITHUB_ACCESS_TOKEN }}
        commentUrl: 'https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/comments'
        prCommentEnabled: true
        device: 'mobile'
        wait: true
